### ISSUE TITLE
CSS: text width too wide?

### ISSUE THREAD

**Issue by kaushalmodi** [pdcawley/bofh.org.uk#1]
Hello,

I came across your https://bofh.org.uk/2022/04/24/not-so-simple/ post through your [tweet](https://twitter.com/pdcawley/status/1518254262362554372).

I am noticing some issues when viewing that page on my browser (Firefox):

- Text width is probably too wide and is flowing out of the right side of my screen.
- The sidenotes are floating on top of the main text.

![image](https://user-images.githubusercontent.com/3578197/165019168-80ffba23-2f87-4f33-bdd3-038b91e96dd3.png)

**Comment by pdcawley** [comment]
Weird. I was messing with the CSS and it looked like that for a while on the local test server, but I didn't think I'd deployed it! 

Time to install Firefox and check.

Thanks for the report.

**Comment by pdcawley** [comment]
Fixed in 0c4ff0d7348aa45c160d8f64f91612a5f55fc7ca

Something weird was happening with the grid, but it turns out I can get the layout I want without using grid layout in body, so I did that.

**Comment by kaushalmodi** [comment]
Cool! I confirm the CSS fix.
